[2024-10-20T17:30:48.034+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T17:30:47.538266+00:00 [queued]>
[2024-10-20T17:30:48.042+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T17:30:47.538266+00:00 [queued]>
[2024-10-20T17:30:48.043+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-20T17:30:48.050+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_cdc_to_redis> on 2024-10-20 17:30:47.538266+00:00
[2024-10-20T17:30:48.053+0000] {standard_task_runner.py:60} INFO - Started process 567 to run task
[2024-10-20T17:30:48.056+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdc_to_minio', 'run_cdc_to_redis', 'manual__2024-10-20T17:30:47.538266+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_cdc_to_minio.py', '--cfg-path', '/tmp/tmps03zikhg']
[2024-10-20T17:30:48.058+0000] {standard_task_runner.py:88} INFO - Job 241: Subtask run_cdc_to_redis
[2024-10-20T17:30:48.089+0000] {task_command.py:423} INFO - Running <TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T17:30:47.538266+00:00 [running]> on host ac960a3ccd9e
[2024-10-20T17:30:48.139+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_to_minio' AIRFLOW_CTX_TASK_ID='run_cdc_to_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T17:30:47.538266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T17:30:47.538266+00:00'
[2024-10-20T17:30:48.140+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-20T17:30:48.141+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/src/kafka_consumer/cdc_to_redis.py']
[2024-10-20T17:30:48.146+0000] {subprocess.py:86} INFO - Output:
[2024-10-20T17:32:03.344+0000] {subprocess.py:93} INFO - Error connect to Redis: Error 111 connecting to redis:6379. Connection refused.
[2024-10-20T17:32:03.366+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-20T17:32:03.396+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cdc_to_minio, task_id=run_cdc_to_redis, execution_date=20241020T173047, start_date=20241020T173048, end_date=20241020T173203
[2024-10-20T17:32:03.415+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-20T17:32:03.429+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
