[2024-10-21T04:23:53.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-21T04:18:51.641555+00:00 [queued]>
[2024-10-21T04:23:53.374+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-21T04:18:51.641555+00:00 [queued]>
[2024-10-21T04:23:53.374+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-10-21T04:23:53.386+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_cdc_to_redis> on 2024-10-21 04:18:51.641555+00:00
[2024-10-21T04:23:53.390+0000] {standard_task_runner.py:60} INFO - Started process 294 to run task
[2024-10-21T04:23:53.392+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdc_to_minio', 'run_cdc_to_redis', 'manual__2024-10-21T04:18:51.641555+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_cdc_to_minio.py', '--cfg-path', '/tmp/tmpx1ib3pdb']
[2024-10-21T04:23:53.394+0000] {standard_task_runner.py:88} INFO - Job 256: Subtask run_cdc_to_redis
[2024-10-21T04:23:53.425+0000] {task_command.py:423} INFO - Running <TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-21T04:18:51.641555+00:00 [running]> on host 0b8c55107464
[2024-10-21T04:23:53.468+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_to_minio' AIRFLOW_CTX_TASK_ID='run_cdc_to_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T04:18:51.641555+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-21T04:18:51.641555+00:00'
[2024-10-21T04:23:53.469+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-21T04:23:53.470+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/src/kafka_consumer/cdc_to_redis.py']
[2024-10-21T04:23:53.474+0000] {subprocess.py:86} INFO - Output:
[2024-10-21T04:23:53.544+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-21T04:23:53.544+0000] {subprocess.py:93} INFO -   File "/opt/***/src/kafka_consumer/cdc_to_redis.py", line 3, in <module>
[2024-10-21T04:23:53.545+0000] {subprocess.py:93} INFO -     from kafka import KafkaConsumer # type: ignore
[2024-10-21T04:23:53.545+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2024-10-21T04:23:53.553+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-21T04:23:53.560+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-21T04:23:53.562+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cdc_to_minio, task_id=run_cdc_to_redis, execution_date=20241021T041851, start_date=20241021T042353, end_date=20241021T042353
[2024-10-21T04:23:53.570+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 256 for task run_cdc_to_redis (Bash command failed. The command returned a non-zero exit code 1.; 294)
[2024-10-21T04:23:53.605+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-21T04:23:53.619+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
