[2024-10-20T18:50:40.383+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T18:50:39.519563+00:00 [queued]>
[2024-10-20T18:50:40.397+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T18:50:39.519563+00:00 [queued]>
[2024-10-20T18:50:40.398+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-20T18:50:40.405+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_cdc_to_redis> on 2024-10-20 18:50:39.519563+00:00
[2024-10-20T18:50:40.407+0000] {standard_task_runner.py:60} INFO - Started process 290 to run task
[2024-10-20T18:50:40.410+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdc_to_minio', 'run_cdc_to_redis', 'manual__2024-10-20T18:50:39.519563+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_cdc_to_minio.py', '--cfg-path', '/tmp/tmps5op2wh6']
[2024-10-20T18:50:40.411+0000] {standard_task_runner.py:88} INFO - Job 245: Subtask run_cdc_to_redis
[2024-10-20T18:50:40.436+0000] {task_command.py:423} INFO - Running <TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T18:50:39.519563+00:00 [running]> on host ac960a3ccd9e
[2024-10-20T18:50:40.477+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_to_minio' AIRFLOW_CTX_TASK_ID='run_cdc_to_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T18:50:39.519563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T18:50:39.519563+00:00'
[2024-10-20T18:50:40.478+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-20T18:50:40.479+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/src/kafka_consumer/cdc_to_redis.py']
[2024-10-20T18:50:40.484+0000] {subprocess.py:86} INFO - Output:
[2024-10-20T18:51:55.970+0000] {subprocess.py:93} INFO - Error connect to Redis: Error 111 connecting to redis:6379. Connection refused.
[2024-10-20T18:51:56.000+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-20T18:51:56.028+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cdc_to_minio, task_id=run_cdc_to_redis, execution_date=20241020T185039, start_date=20241020T185040, end_date=20241020T185156
[2024-10-20T18:51:56.043+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-20T18:51:56.060+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
