[2024-10-20T16:08:59.886+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T16:08:58.619683+00:00 [queued]>
[2024-10-20T16:08:59.890+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T16:08:58.619683+00:00 [queued]>
[2024-10-20T16:08:59.890+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-10-20T16:08:59.902+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_cdc_to_redis> on 2024-10-20 16:08:58.619683+00:00
[2024-10-20T16:08:59.908+0000] {standard_task_runner.py:60} INFO - Started process 3435 to run task
[2024-10-20T16:08:59.912+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdc_to_minio', 'run_cdc_to_redis', 'manual__2024-10-20T16:08:58.619683+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_cdc_to_minio.py', '--cfg-path', '/tmp/tmpf__959ec']
[2024-10-20T16:08:59.914+0000] {standard_task_runner.py:88} INFO - Job 233: Subtask run_cdc_to_redis
[2024-10-20T16:08:59.945+0000] {task_command.py:423} INFO - Running <TaskInstance: cdc_to_minio.run_cdc_to_redis manual__2024-10-20T16:08:58.619683+00:00 [running]> on host 971d6e3a7621
[2024-10-20T16:08:59.985+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdc_to_minio' AIRFLOW_CTX_TASK_ID='run_cdc_to_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T16:08:58.619683+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T16:08:58.619683+00:00'
[2024-10-20T16:08:59.986+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-20T16:08:59.986+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/src/kafka_consumer/cdc_to_redis.py']
[2024-10-20T16:08:59.993+0000] {subprocess.py:86} INFO - Output:
[2024-10-20T16:09:00.079+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-10-20T16:09:00.079+0000] {subprocess.py:93} INFO -   File "/opt/***/src/kafka_consumer/cdc_to_redis.py", line 3, in <module>
[2024-10-20T16:09:00.080+0000] {subprocess.py:93} INFO -     from kafka import KafkaConsumer
[2024-10-20T16:09:00.080+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2024-10-20T16:09:00.087+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-20T16:09:00.094+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-20T16:09:00.095+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdc_to_minio, task_id=run_cdc_to_redis, execution_date=20241020T160858, start_date=20241020T160859, end_date=20241020T160900
[2024-10-20T16:09:00.102+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 233 for task run_cdc_to_redis (Bash command failed. The command returned a non-zero exit code 1.; 3435)
[2024-10-20T16:09:00.128+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-20T16:09:00.140+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
